# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MDE
                                 A QGIS plugin
 Aquisição de Modelo de Elevação Topodata e processamento de MDE
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-15
        copyright            : (C) 2020 by Fabrício Amorim
        email                : fabricioamorimeac@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MDE class from file MDE.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MDE import MDE
    return MDE(iface)
